### ISSUE TITLE
Dynamic Pricing of Tickets

### ISSUE THREAD

**Issue by RealJammy** [NicholasG04/Prom#176]
As we draw closer to Prom, I propose the price of tickets increasing exponentially.  
I'll suggest using `y=-x^{0.82}+80`, where x is the number of days left to prom and y is the final ticket price. This would help encourage people to buy now, with fear or them saying prices are kind of ridiculous tbh, while allowing those richer enough to hold back on their plans for later, in case people are worried that prom looks 90038847457383 times better than it actually is. Furthermore, if prom plans all fall through, it'll be a pain in the arse for the richer students, allowing you to maximise profits without causing harm to those in financial hardship.

Overall, while the dev team may think that We shouldnt do ahh if that, it is highly worth it, to maximise profits.

**Comment by john-montgomery2003** [comment]
Interesting thought

**Comment by john-montgomery2003** [comment]
One issue I'm seeing is you haven't factored in for the possibility of time travel, a junior level error really. I would suggest we chuck an abs around it (because if they can time travel they are rich, and the further they can travel the more they can shell out). By my calculations your model will make it cost the prom money if they pay more than 210 days in advance. Frankly this won't work, as this was Friday the 10th of December 2021, a date which even a basic time traveling machine should be able to reach. For your approval, I will give some key historical dates to show how much it would cost if bought on those days according to my model.

- 1st December 2003, my dob = £1366.71
- 1st January 2000, millennium = £1548.04
- 14th October 1066, battle of Hastings = £35,010.73

Would this change be accepted?

**Comment by john-montgomery2003** [comment]
@NicholasG04 I think we need you on this one please

**Comment by NicholasG04** [comment]
Wow. I'll pass these comments on to the team: @Modlizard really likes statistics, maybe you could take a look?

**Comment by john-montgomery2003** [comment]
Sounds good! I'm really excited to see these pushed into prod ASAP!

**Comment by john-montgomery2003** [comment]
Don't worry about that just admin stuff that has to be done

**Comment by RealJammy** [comment]
> One issue I'm seeing is you haven't factored in for the possibility of time travel, a junior level error really. I would suggest we chuck an abs around it (because if they can time travel they are rich, and the further they can travel the more they can shell out). By my calculations your model will make it cost the prom money if they pay more than 210 days in advance. Frankly this won't work, as this was Friday the 10th of December 2021, a date which even a basic time traveling machine should be able to reach. For your approval, I will give some key historical dates to show how much it would cost if bought on those days according to my model.
> 
> * 1st December 2003, my dob = £1366.71
> * 1st January 2000, millennium = £1548.04
> * 14th October 1066, battle of Hastings = £35,010.73
> 
> Would this change be accepted?

Hiya Mr Montgomery, surely if someone had the ability to time travel, then they should be rewarded by the Prom Committee for their innovative research. Due to the customers being part of a STEM college, surely we should vouchsafe those with intellect money, no?

**Comment by john-montgomery2003** [comment]
We aren't some charity in the business of furthering science. We're here for pure capitalist gains.

**Comment by john-montgomery2003** [comment]
I want to quit lifeguarding and live off nft investments, I just need the start up capital from prom

**Comment by Modlizard** [comment]
I concur that prices should indeed, exponentially, increase however I believe that it would be substantially advantageous to introduce an aspect of volatility by varying the price of tickets every 5 or so minutes (300 seconds). The median price of tickets for a given day would still be given by the aforementioned equation however additional equations will be used in order to vary the range of prices for the ticket on a given day. The equation for the lower and upper bounds of a price will be given by the functions `y=g(x)` and `y=f(x)` retrogradely (inverse of respectively) where the operations applied by f(x) as well as g(x) are trivial and left as an exercise to the reader. Finally, due to security concerns around the exploitation of our now fluid ticket market through the use of analysis and random number generation algorithm derivation and prediction, we will be using a radioactivity based random number generator alongside a four hundred and twenty gram (~14.8151 oz) deposit of Caesium-137.

**Comment by RealJammy** [comment]
> I want to quit lifeguarding and live off nft investments, I just need the start up capital from prom

That brings me onto my next point, making each ticket a NFT.

**Comment by john-montgomery2003** [comment]
> > I want to quit lifeguarding and live off nft investments, I just need the start up capital from prom
> 
> That brings me onto my next point, making each ticket a NFT.

This is a duplicate issue, already closed, please don't waste the dev time. Smh...

**Comment by Modlizard** [comment]
> > > I want to quit lifeguarding and live off nft investments, I just need the start up capital from prom
> > 
> > 
> > That brings me onto my next point, making each ticket a NFT.
> 
> This is a duplicate issue, already closed, please don't waste the dev time. Smh...

User feedback is extremely important and should not be dismissed; we will, of course, be closely working with our clients to deliver the best possible prom experience.

**Comment by john-montgomery2003** [comment]
> > > > I want to quit lifeguarding and live off nft investments, I just need the start up capital from prom
> > > 
> > > 
> > > That brings me onto my next point, making each ticket a NFT.
> > 
> > This is a duplicate issue, already closed, please don't waste the dev time. Smh...
> 
> I apologise, Mr Montgomery.

No need to apologise, or call me Mr Montgomery. Call me john, we are both friends of the great Nicholas Gregory, the friend of my friend is my friend.

**Comment by NicholasG04** [comment]
Users are very reluctant to buy tickets knowing they can wait until closer to the time, so implementing this may meliorate our cash flow situation. I would suggest prioritising this ASAP.

**Comment by RealJammy** [comment]
After speaking with @NicholasG04 , I think we should adjust the formula to `y=|-x^{1.69420}+1000|`, so people are ripped off fairly, not to mention us not having to pay out in the case of time travel, with this potentially acting as a penalty. @john-montgomery2003 Please vouchsafe me with your thoughts on this.

**Comment by john-montgomery2003** [comment]
> After speaking with @NicholasG04 , I think we should adjust the formula to `y=|-x^{1.69420}+1000|`, so people are ripped off fairly, not to mention us not having to pay out in the case of time travel, with this potentially acting as a penalty. @john-montgomery2003 Please vouchsafe me with your thoughts on this.

Approved. @Modlizard  do your scrum shit make it happen.

**Comment by Modlizard** [comment]
After scrutinous, statistical analysis the team has concluded that this will be a beneficial enhancement and we will therefore forward this to our web development team consisting of @NicholasG04 and @JacquesRW.

**Comment by RealJammy** [comment]
@NicholasG04 @JacquesRW any ETA on when this issue will be resolved?

**Comment by NicholasG04** [comment]
I've delegated to @Modlizard and @john-montgomery2003, but thanks.

**Comment by Modlizard** [comment]
I've superdelegated the issue unto @JacquesRW @NicholasG04.

**Comment by NicholasG04** [comment]
Not being used
